import { createElement } from '@lwc/engine-dom';
import C2pParentEventListener from 'c/c2pParentEventListener';

describe('c-c2-p-parent-event-listener', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-c2-p-parent-event-listener', {
            is: C2pParentEventListener
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});